#!/usr/bin/env bash
#prints 1 - 100 except fizz buzz
for i in {1..100}
do
	if [ $((i%3)) -ne 0 -a $((i%5)) -ne 0 ]
	then
		echo $i
	else
		if [ $((i%3)) -eq 0 ]
		then
			printf "Fizz"
		fi
		if [ $((i%5)) -eq 0 ]
		then
			printf "Buzz"
		fi
			printf "\n"
	fi
done
